---
title: "Untitled"
author: "Lukas Schumacher"
date: "2/10/2021"
output: html_document
---

Diffusion modeling of the visual duration discrimination task (exp 2) of dyjas et al. (2012)

### Load final data
```{r}
library(tidyverse)
library(brms)
library(rstan)
library(bayesplot)
library(magrittr)
library(lemon)
library(viridis)
library(tidybayes)
library(BayesianFROC)
library(ggthemes)
library(latex2exp)
library(rcartocolor)

# load final data // skip data preparation section
setwd("/users/lukas/documents/github/timing_discrimination/data/")
df <- read.csv("exp2_cond_C.csv")

color_palette <- c("#2E5868","#B06988")
```

### Data preperation
```{r}
setwd("/users/lukas/documents/UniHeidel/Project_Discrimination/Dyjas Bausenhart Ulrich 2012/Experiment 2")

# Read all files into one data frame
files = list.files(pattern="*D.txt")
df = NULL
for (f in files) {
  sub=as.numeric(substr(f,10,nchar(f)-5))
  # if(sub==99) next
  data = read.table(f, skip=30)
  colnames(data) = c("trl", "cpos", "cdur", "resp", "RT", "type")
  data$d1 = ifelse(data$cpos==2, 500, data$cdur)
  data$d2 = ifelse(data$cpos==2, data$cdur, 500)
  
  df=rbind(
    df,
    cbind(
      sub=sub,
      data)
  )
}

# arrange by sub
df %<>%
  mutate(sub=as.numeric(sub)) %>% 
  arrange(sub)

# Remove NA response
df[df$resp<1 | df$resp>2,"resp"] = NA
df = na.omit(df)
```

#### EWMA
```{r}
# calculate correct response
df$correct <- NA
for (i in 1:nrow(df)) {
  if(df$cpos[i]==1 & df$cdur[i]>500){
    if(df$resp[i]==1){
      df$correct[i] <- 1
    }else{
      df$correct[i] <- 0
    }
  }else if(df$cpos[i]==1 & df$cdur[i]<500){
    if(df$resp[i]==2){
      df$correct[i] <- 1
    }else{
      df$correct[i] <- 0
    }
  }else if(df$cpos[i]==2 & df$cdur[i]>500){
    if(df$resp[i]==2){
      df$correct[i] <- 1
    }else{
      df$correct[i] <- 0
    }
  }else if(df$cdur[i]==500){
    df$correct[i] <- 0
  }
  else{
    if(df$resp[i]==1){
      df$correct[i] <- 1
    }else{
      df$correct[i] <- 0
    }
  }
}

# Define constants
lambda   <- 0.01  # weight param (how many previous data points)
c_0      <- 0.5   # in-control mean (expected average performance for fast guess)
sigma_0  <- 0.5   # in-control sd
L        <- 1.5   # sensitivity (1.5 is a relative low value)

# Compute EMWA
data <- data.frame()
for (s in unique(df$sub)) {
  
  tmp <- df %>% 
    filter(sub==s) %>% 
    arrange(RT)
  
  tmp$c_s <- NA
  tmp$inCm <- "empty"
  tmp$UCL <- NA
  
  c_before <- c_0
  
  # Compute EWMA for each data point
  for (i in 1:length(tmp$RT)) {
    if(tmp$cdur[i]==500) next
    tmp$c_s[i] <- (lambda*tmp$correct[i]) + ((1-lambda)*c_before)
    tmp$UCL[i] <- c_0 + (L*sigma_0)*sqrt((lambda/(2-lambda))*(1-(1-lambda)^(2*i)))
    tmp$inCm[i] <- tmp$c_s[i] < tmp$UCL[i]
    c_before <- tmp$c_s[i]
  }
  
  data <- rbind(data,tmp)
}

# plot EWMA control chart
data %>%
  filter(inCm != "empty") %>% 
  mutate(inCm=as.logical(inCm)) %>% 
  ggplot(aes(x=RT,
             y=c_s,
             color=(inCm>0)))+
  geom_line(aes(group=2),
            size=0.3)+
  geom_hline(yintercept = 0.5,
             linetype="dotted")+
  geom_line(aes(x=RT,
                y=UCL,
                color="black"))+
  scale_color_manual(values=c("#453b44","#39C8C6","#630C3A"))+
  xlab("\nReaction time (s)")+
  ylab(TeX("State of the system ($c_s$)"))+
  ggtitle("EWMA control chart")+
  theme_tufte(base_family = "GillSans")+
  theme(legend.position="none",
        axis.line = element_line(size = .5, color = "#444444"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))+
  scale_x_continuous(limits = c(0,2000))+
  facet_wrap(~sub)
```

#### Fast guesses
```{r}
# check proportion of fast guesses for each sub
data %>%
  filter(inCm==TRUE,
         cdur!=500,
         RT<100) %>% 
  group_by(sub) %>% 
  summarise(acc=round(mean(correct),2),
            rt=round(mean(RT),3),
            n=length(correct),
            prob=round(n/660,2))

# check proportion of very slow responses for each sub
data %>%
  filter(cdur!=500,
         RT>2000) %>% 
  group_by(sub) %>% 
  summarise(acc=round(mean(correct),2),
            rt=round(mean(RT),3),
            n=length(correct),
            prob=round(n/660,2))

# overall accuracy
data %>%
  filter(cdur!=500) %>% 
  group_by(sub) %>% 
  summarise(acc=round(mean(correct),2),
            rt=round(mean(RT),3),
            n=length(correct))

# cut 7, 10, 19
# remove non-cooperative participants and fast guesses and slow responses
df <- data %>% 
  filter(sub!=7,
         sub!=10,
         sub!=19) %>% 
  mutate(inCm=as.character(inCm)) %>% 
  filter(inCm!="TRUE",
         RT>100,
         RT<2000)

# rearrange
df %<>% arrange(sub,trl)

# reassign sub nr
df %<>%
  mutate(sub=as.numeric(sub)) %>% 
  arrange(sub)
nr <- 1
for (i in 2:length(df$sub)){
  if(df$sub[i]!=df$sub[i-1]){
    nr <- nr+1
    df$sub[df$sub==df$sub[i]] <- nr
  }
}
# save final data
write_csv(df,"/users/lukas/documents/github/timing_discrimination/data/exp2_cond_C.csv")

```


#### DL and PSE
```{r}
# function for transform probability to logit
prob2logit <- function(prob){
  logit <- log(prob/(1-prob))
  return(logit)
}

df$DL_1 <- NA
df$DL_2 <- NA
df$PSE_1 <- NA
df$PSE_2 <- NA

for (s in unique(df$sub)) {
  tmp <- df %>% 
  filter(sub==s) %>% 
  mutate(resp=2-resp,
         cpos=as.factor(cpos),
         cdur=(cdur-500))
  
  tmp$resp[tmp$cpos==2] <- 1 - tmp$resp[tmp$cpos==2]
  
  # logstic regression for psychometric curve
  logReg <- tmp %>%
    brm(formula = resp~cdur*cpos,
        family = bernoulli(),
        chains = 4,
        iter = 1000,
        cores=parallel::detectCores(),
        control = list(adapt_delta=0.95))

  params <- as.numeric(as.data.frame(logReg) %>% colMeans())

  # DL and PSE for cpos = 1
  c25_1 <- (prob2logit(0.25)-params[1])/params[2]
  df$PSE_1[df$sub==s] <- (prob2logit(0.50)-params[1])/params[2]
  c75_1 <- (prob2logit(0.75)-params[1])/params[2]
  df$DL_1[df$sub==s] <- (c75_1 - c25_1)/2
  # DL and PSE for cpos = 2
  c25_2 <- (prob2logit(0.25)-params[1]-params[3])/(params[2]+params[4])
  df$PSE_2[df$sub==s] <- (prob2logit(0.50)-params[1]-params[3])/(params[2]+params[4])
  c75_2 <- (prob2logit(0.75)-params[1]-params[3])/(params[2]+params[4])
  df$DL_2[df$sub==s] <- (c75_2 - c25_2)/2
}

summary_emp_DL_PSE <- df %>% 
  group_by(sub) %>% 
  summarise(DL_1=DL_1[1],
            DL_2=DL_2[1],
            PSE_1=PSE_1[1],
            PSE_2=PSE_2[1]) %>% 
  mutate(DL_diff=DL_2-DL_1,
         PSE_dff=abs(PSE_2)-abs(PSE_1))

df %<>%
    mutate(DL_diff=DL_2-DL_1,
         PSE_diff=abs(PSE_2)-abs(PSE_1))

```



### Psychometrics
```{r}
summary <- df %>%
  group_by(sub,
           cdur,
           cpos) %>% 
  mutate(resp=2-resp) %>% 
  summarise(prob_c = mean(resp))

summary$prob_c[summary$cpos==2] <- 1 - summary$prob_c[summary$cpos==2]
summary$cpos <- as.factor(summary$cpos)

color_palette <- c("#2E5868","#B06988")
summary %>% ggplot(aes(x=cdur,
                       y=prob_c,
                       color=cpos))+
  geom_line(size=0.8)+
  geom_point(size=1)+
  geom_hline(yintercept=0.5,
             linetype="dashed")+
  facet_wrap(~sub)+
  scale_x_continuous(breaks=unique(summary$cdur),
                     labels=unique(summary$cdur),
                     expand = c(0.01,0.01))+
  ggthemes::theme_tufte()+
  scale_color_manual(values = color_palette)+
  scale_fill_manual(values = color_palette,
                    guide=F)+
  scale_linetype_manual(values=c("solid","dashed"))+
  ylab("Probability for c > s response")+
  xlab("\nDuration of c")+
  labs(color = "Position of c")+
  theme(axis.line = element_line(size = .5, color = "#969696"),
        axis.ticks = element_line(color = "#969696"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))

```
### RT distributions
```{r}
df %>% 
  ggplot(aes(x=RT)) + 
  geom_density() +
  facet_wrap(~sub)+
  ggthemes::theme_tufte()+
  scale_color_manual(values = color_palette)+
  scale_fill_manual(values = color_palette,
                    guide=F)+
  scale_linetype_manual(values=c("solid","dashed"))+
  ylab("Probability for c > s response")+
  xlab("\nDuration of c")+
  labs(color = "Position of c")+
  theme(axis.line = element_line(size = .5, color = "#969696"),
        axis.ticks = element_line(color = "#969696"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))

```

### Fitting preparation
```{r}
# set working directory to the location of the stan models
setwd("/users/lukas/documents/github/timing_discrimination/models")

# get number of participants
S = length(unique(df$sub))

# arrange rows of df after sub and then trial
df <- df %>% 
  arrange(sub,trl)

# create stan data
stan_data = list(
  `T`  = nrow(df),
  S    = S,
  sub  = df$sub,
  d1   = df$d1-500,
  d2   = df$d2-500,
  resp = df$resp,
  rt   = df$RT / 1000
)

# set initial values
init = function(chains=4) {
  L = list()
  for (c in 1:chains) {
    L[[c]]=list()
    
    L[[c]]$mu_a   = 1.0
    L[[c]]$mu_ndt = 0.1
    L[[c]]$mu_z0  = 0.5
    L[[c]]$mu_bz  = 0.0
    L[[c]]$mu_v0  = 1.0
    L[[c]]$mu_bv  = 0.0
    L[[c]]$mu_b1v = 0.0
    L[[c]]$mu_b2v = 0.0
    L[[c]]$mu_g   = 0.5
    
    L[[c]]$sd_a   = 0.001
    L[[c]]$sd_ndt = 0.001
    L[[c]]$sd_z0  = 0.001
    L[[c]]$sd_bz  = 0.001
    L[[c]]$sd_v0  = 0.001
    L[[c]]$sd_bv  = 0.001
    L[[c]]$sd_b1v = 0.001
    L[[c]]$sd_b2v = 0.001
    L[[c]]$sd_g   = 0.001
    
    L[[c]]$a = rep(1,S)
    L[[c]]$z0 = rep(0.5,S)
    L[[c]]$bz = rep(0.0,S)
    L[[c]]$v0 = rep(1.0,S)
    L[[c]]$bv = rep(0.0,S)
    L[[c]]$b1v = rep(0.0,S)
    L[[c]]$b2v = rep(0.0,S)
    L[[c]]$ndt = rep(0.1,S)
    L[[c]]$g = rep(0.5,S)
  }
  return (L)
}

```

### Model 9
```{r}
fit_m9 <-  stan("hierarchical_m9.stan",
                         init=init(4),
                         data=stan_data,
                         chains=4,
                         iter = 2000,
                         cores=parallel::detectCores(),
                         control = list(adapt_delta=0.99,
                                        max_treedepth=15))

# saveRDS(fit_m11,"/users/lukas/documents/UniHeidel/Project_Discrimination/fits/fit_m11_new.rds")
```

### Model evaluation
```{r}
setwd("/users/lukas/documents/UniHeidel/Project_Discrimination/fits")
m1 <- readRDS("fit_m1_exp2.rds")
m2 <- readRDS("fit_m2_exp2.rds")
setwd("/users/lukas/documents/UniHeidel/Project_Discrimination/fits")
m3 <- readRDS("fit_m3_exp2.rds")
m6 <- readRDS("fit_m6_exp2.rds")
m7 <- readRDS("fit_m7_exp2.rds")
setwd("/users/lukas/documents/UniHeidel/Project_Discrimination/fits")
m8 <- readRDS("fit_m8_exp2.rds")
m9 <- readRDS("fit_m9_exp2.rds")

check_hmc_diagnostics(m1)
check_hmc_diagnostics(m2)
check_hmc_diagnostics(m3)
check_hmc_diagnostics(m6)
check_hmc_diagnostics(m7)
check_hmc_diagnostics(m8)
check_hmc_diagnostics(m9)

pars <- c("mu_a","mu_ndt","mu_z0","mu_bz","mu_v0","mu_b1v","mu_b2v", "mu_g",
          "sigma_a","sigma_ndt","sigma_z0","sigma_bz","sigma_v0","sigma_b1v","sigma_b2v", "sigma_g")
traceplot(m9,pars=pars)

# compute loo
loo_m1 <- loo(m1)
loo_m2 <- loo(m2)
loo_m3 <- loo(m3)
loo_m6 <- loo(m6)
loo_m7 <- loo(m7)
loo_m8 <- loo(m8)
loo_m9 <- loo(m9)

# compare goodness-of-fit
comparison <- loo_compare(loo_m1,
                          loo_m2,
                          loo_m6,
                          loo_m3,
                          loo_m8,
                          loo_m7,
                          loo_m9)

comparison %<>% 
  as_tibble(rownames = "model") %>% 
  mutate(model=str_replace_all(model,"(.{5})", "\\1 "),
         exp=2)

# write.csv(comparison,"/users/lukas/documents/UniHeidel/Project_Discrimination/fits/loo_comparison_exp2.csv")
comparison_exp1 <- read_csv("/users/lukas/documents/UniHeidel/Project_Discrimination/fits/loo_comparison_exp1.csv")
comparison_exp2 <- read_csv("/users/lukas/documents/UniHeidel/Project_Discrimination/fits/loo_comparison_exp2.csv")

comparison <- rbind(comparison_exp1,comparison_exp2) %>% 
  select(-X1)

```

```{r}
tiff('/users/lukas/desktop/model_comp.tiff', units="in", width=10, height=5, res=1200)
comparison %>% 
  rename(Experiment=exp) %>% 
  ggplot(aes(x = elpd_diff,
         y = model))+
  geom_point(color=carto_pal(7, "BurgYl")[7],
             size=3.5)+
  geom_linerange(aes(xmin=elpd_diff-se_diff*5,
                      xmax=elpd_diff+se_diff*5),
                 color="#B06988",
                 size=1)+
  geom_linerange(aes(xmin=elpd_diff-se_diff,
                      xmax=elpd_diff+se_diff),
                  color=carto_pal(7, "BurgYl")[7],
                  size=2.5)+
  geom_vline(xintercept = 0,
             linetype="dashed",
             color="#969696")+
  ggthemes::theme_tufte()+
  ylab("Model")+
  xlab("\nDifference in Elpd")+
  theme(axis.line = element_line(size = .5, color = "#969696"),
        axis.ticks = element_line(color = "#969696"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))+
  facet_wrap(~Experiment, ncol=1,
             labeller = label_both)
dev.off()
```



```{r}
pars <- c("mu_a","mu_ndt","mu_z0","mu_bz","mu_v0","mu_b1v","mu_b2v","mu_g")
mcmc_pairs(m9,
           pars=pars)

```

```{r}
pars <- c("bz[1]","bz[2]","bz[3]","bz[4]","bz[5]","bz[6]","bz[7]","bz[8]","bz[9]","bz[10]","bz[11]","bz[12]","bz[13]","bz[14]","bz[15]","bz[16]","bz[17]","bz[18]","bz[19]","bz[20]","bz[21]")
print(m9,pars=pars,digits=5)


individual_g <- summary(m9,pars=c("g[1]","g[2]","g[3]","g[4]","g[5]","g[6]","g[7]","g[8]","g[9]","g[10]","g[11]","g[12]","g[13]","g[14]","g[15]","g[16]","g[17]","g[18]","g[19]","g[20]","g[21]"))$summary[,"mean"]
individual_b1v <- summary(m9,pars=c("b1v[1]","b1v[2]","b1v[3]","b1v[4]","b1v[5]","b1v[6]","b1v[7]","b1v[8]","b1v[9]","b1v[10]","b1v[11]","b1v[12]","b1v[13]","b1v[14]","b1v[15]","b1v[16]","b1v[17]","b1v[18]","b1v[19]","b1v[20]","b1v[21]"))$summary[,"mean"]
individual_b2v <- summary(m9,pars=c("b2v[1]","b2v[2]","b2v[3]","b2v[4]","b2v[5]","b2v[6]","b2v[7]","b2v[8]","b2v[9]","b2v[10]","b2v[11]","b2v[12]","b2v[13]","b2v[14]","b2v[15]","b2v[16]","b2v[17]","b2v[18]","b2v[19]","b2v[20]","b2v[21]"))$summary[,"mean"]
individual_z0 <- summary(m9,pars=c("z0[1]","z0[2]","z0[3]","z0[4]","z0[5]","z0[6]","z0[7]","z0[8]","z0[9]","z0[10]","z0[11]","z0[12]","z0[13]","z0[14]","z0[15]","z0[16]","z0[17]","z0[18]","z0[19]","z0[20]","z0[21]"))$summary[,"mean"]

sumsum <- df %>% 
  group_by(sub) %>% 
  summarise(typeB=DL_diff[1],
            typeA=PSE_diff[1])

sumsum <- cbind(sumsum,
                individual_b1v,
                individual_b2v,
                individual_g,
                individual_z0)

sumsum$weightdiff_percent <- (abs(sumsum$individual_b1v) - abs(sumsum$individual_b2v))/(abs(sumsum$individual_b1v) + abs(sumsum$individual_b2v))

cor(sumsum$typeB,individual_g)
cor(sumsum$typeB,sumsum$weightdiff_percent)
cor(sumsum$typeA,sumsum$individual_z0)

```



```{r}
pars <- c("mu_a","mu_ndt","mu_z0","mu_bz","mu_v0","mu_b1v","mu_b2v","mu_g")
mat <- summary(m9,pars=pars)$summary[,"mean"]

# experiment settings
nTrials <- nrow(df)
d1 = df$d1-500
d2 = df$d2-500
cdur <- df$cdur
cpos <- as.numeric(df$cpos)

discrimination_ddm_sim <- function(nTrials, mat){
  
  setwd("/Users/lukas/documents/UniHeidel/code")
  source("wienerProcess.R")
  library(svMisc)
  
  data <- data.frame(matrix(ncol=8,nrow=0, dimnames=list(NULL, c("resp", "rt","I","delta","d1","d2","cdur","cpos"))))
  
  a <- mat[1]
  ndt <- mat[2]
  z <- mat[3]
  bz <- mat[4]
  v0 <- mat[5]
  b1v <- mat[6]
  b2v <- mat[7]
  g <- mat[8]
  
  I <- rep(NA,nTrials)
  
  for (i in 1:nTrials) {
    
    if (i == 1) {
      I[1] <-  d1[1]
    } else if (df$sub[i] != df$sub[i-1]) {
      I[i] <-  df$d1[i]
    } else
      I[i] = g*I[i-1] + (1-g)*d1[i]
    
    beta = z + bz * I[i]
    delta <-  v0 + b1v * I[i] + b2v * d2[i]
    
    data <- data %>% add_row(wienerProcess(v=delta, a=a, z=beta, ndt=ndt),
                             I=I[i],delta=delta,d1=d1[i],d2=d2[i],cdur=cdur[i],cpos=cpos[i])
  }
    
  return(data)
}

pred_m9 <- discrimination_ddm_sim(nTrials,mat)
pred_m9$cpos <- as.factor(pred_m9$cpos)

```

```{r}
df_summary <- df %>% 
  group_by(cpos,
           cdur) %>% 
  summarise(prob_c=mean(resp)) %>% 
  mutate(cpos=as.factor(cpos),
         prob_c=prob_c-1)

df_summary$prob_c[df_summary$cpos==1] <- 1 - df_summary$prob_c[df_summary$cpos==1]


summary_pred_m9 <- pred_m9 %>% 
  group_by(cpos,
           cdur) %>% 
  summarise(prob_c=mean(resp)) %>% 
  mutate(cpos=as.factor(cpos))

summary_pred_m9$prob_c[summary_pred_m9$cpos==2] <- 1 - summary_pred_m9$prob_c[summary_pred_m9$cpos==2]


summary_pred_m9$cpos <- as.factor(summary_pred_m9$cpos)
color_palette <- c("#2E5868","#B06988")
summary_pred_m9 %>%
  ggplot(aes(x=cdur,
             y = prob_c,
             color=cpos))+
  geom_line(size=0.8)+
  geom_point(size=1)+
  geom_point(data=df_summary,
             mapping=aes(x=cdur,
                         y=prob_c,
                         color=cpos),
             shape=3,
             size=4)+
  geom_line(data=df_summary,
            mapping=aes(x=cdur,
                        y=prob_c,
                        color=cpos),
            linetype="dashed")+
  scale_x_continuous(breaks=unique(summary_pred_m9$cdur),
                     labels=unique(summary_pred_m9$cdur),
                     expand = c(0.01,0.01))+
  ggthemes::theme_tufte()+
  scale_color_manual(values = color_palette)+
  scale_fill_manual(values = color_palette,
                    guide=F)+
  scale_linetype_manual(values=c("solid","dashed"))+
  ylab("Probability for c > s response")+
  xlab("\nDuration of c")+
  labs(color = "Position of c")+
  theme(axis.line = element_line(size = .5, color = "#969696"),
        axis.ticks = element_line(color = "#969696"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))
```

```{r}
pars <- c("mu_a","mu_ndt","mu_z0","mu_v0","mu_b1v","mu_b2v")
mcmc_pairs(m6,
           pars=pars)
```


```{r}
mat <- summary(m6,pars=pars)$summary[,"mean"]

# experiment settings
nTrials <- nrow(df)
d1 = df$d1-500
d2 = df$d2-500
cdur <- df$cdur
cpos <- as.numeric(df$cpos)

discrimination_ddm_sim <- function(nTrials, mat){
  
  setwd("/Users/lukas/documents/UniHeidel/code")
  source("wienerProcess.R")
  library(svMisc)
  
  data <- data.frame(matrix(ncol=7,nrow=0, dimnames=list(NULL,c("resp", "rt","delta","d1","d2","cdur","cpos"))))
  
  a <- mat[1]
  ndt <- mat[2]
  z <- mat[3]
  v0 <- mat[4]
  b1v <- mat[5]
  b2v <- mat[6]
  
  delta <-  v0 + b1v * d1 + b2v * d2
  
  for (i in 1:nTrials) {
    data <- data %>% add_row(wienerProcess(v=delta[i], a=a, z=z, ndt=ndt),
                             delta=delta[i],d1=d1[i],d2=d2[i],cdur=cdur[i],cpos=cpos[i])
  }

  return(data)
}

pred_m6 <- discrimination_ddm_sim(nTrials,mat)
```

```{r}
df_summary <- df %>% 
  group_by(cpos,
           cdur) %>% 
  summarise(prob_c=mean(resp)) %>% 
  mutate(cpos=as.factor(cpos),
         prob_c=prob_c-1)

df_summary$prob_c[df_summary$cpos==1] <- 1 - df_summary$prob_c[df_summary$cpos==1]

summary_pred_m6 <- pred_m6 %>% 
  group_by(cpos,
           cdur) %>% 
  summarise(prob_c=mean(resp)) %>% 
  mutate(cpos=as.factor(cpos))

summary_pred_m6$prob_c[summary_pred_m6$cpos==2] <- 1 - summary_pred_m6$prob_c[summary_pred_m6$cpos==2]


summary_pred_m6$cpos <- as.factor(summary_pred_m6$cpos)
color_palette <- c("#2E5868","#B06988")
summary_pred_m6 %>%
  ggplot(aes(x=cdur,
             y = prob_c,
             color=cpos))+
  geom_line(size=0.8)+
  geom_point(size=1)+
  geom_point(data=df_summary,
             mapping=aes(x=cdur,
                         y=prob_c,
                         color=cpos),
             shape=3,
             size=4)+
  geom_line(data=df_summary,
            mapping=aes(x=cdur,
                        y=prob_c,
                        color=cpos),
            linetype="dashed")+
  scale_x_continuous(breaks=unique(summary_pred_m6$cdur),
                     labels=unique(summary_pred_m6$cdur),
                     expand = c(0.01,0.01))+
  ggthemes::theme_tufte()+
  scale_color_manual(values = color_palette)+
  scale_fill_manual(values = color_palette,
                    guide=F)+
  scale_linetype_manual(values=c("solid","dashed"))+
  ylab("Probability for c > s response")+
  xlab("\nDuration of c")+
  labs(color = "Position of c")+
  theme(axis.line = element_line(size = .5, color = "#969696"),
        axis.ticks = element_line(color = "#969696"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        text=element_text(size = 16),
        plot.title = element_text(size =18,
                                  hjust = 0.5),
        axis.title.y = element_text(vjust = 0.5,
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)))
```

### Subject prediction
```{r sloppy posterior extraction}
mat <- as.data.frame(m6) %>%
  select(starts_with(c("a[","ndt[","z0[","v0[","b1v[","b2v")))

numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
}

a <- mat %>% 
  select(`a[1]`:`a[21]`) %>% 
  pivot_longer(cols = `a[1]`:`a[21]`,
               names_to = "sub",
               values_to = "a") %>% 
  mutate(sample=rep(seq(1,nrow(mat)),each=nrow(.)/nrow(mat)),
         sub=numextract(sub)) %>% 
  select(sample,sub,a)

ndt <- mat %>% 
  select(`ndt[1]`:`ndt[21]`) %>% 
  pivot_longer(cols = `ndt[1]`:`ndt[21]`,
               names_to = "sub",
               values_to = "ndt") %>% 
  select(ndt)

z0 <- mat %>% 
  select(`z0[1]`:`z0[21]`) %>% 
  pivot_longer(cols = `z0[1]`:`z0[21]`,
               names_to = "sub",
               values_to = "z0") %>% 
  select(z0)

v0 <- mat %>% 
  select(`v0[1]`:`v0[21]`) %>% 
  pivot_longer(cols = `v0[1]`:`v0[21]`,
               names_to = "sub",
               values_to = "v0") %>% 
  select(v0)

b1v <- mat %>% 
  select(`b1v[1]`:`b1v[21]`) %>% 
  pivot_longer(cols = `b1v[1]`:`b1v[21]`,
               names_to = "sub",
               values_to = "b1v") %>% 
  select(b1v)

b2v <- mat %>% 
  select(`b2v[1]`:`b2v[21]`) %>% 
  pivot_longer(cols = `b2v[1]`:`b2v[21]`,
               names_to = "sub",
               values_to = "b2v") %>% 
  select(b2v)

mat <- cbind(a,ndt,z0,v0,b1v,b2v)
```


```{r}
# posterior samples thinning
mat <- mat[mat$sample %in% seq(1,max(mat$sample), by=200),]

discrimination_ddm_sim <- function(mat){
  
  setwd("/Users/lukas/documents/UniHeidel/code")
  source("wienerProcess.R")
  library(svMisc)
  
  data <- data.frame(matrix(ncol=8,nrow=0,
                            dimnames=list(NULL, c("dataset","sub","d1","d2","cdur","cpos","resp", "rt"))))
  
  # iterate over posterior samples
  for (t in unique(mat$sample)){
    
    # iterate over subjects
    for (s in 1:length(unique(mat$sub))){
      a   <- mat$a[mat$sample==t][s]
      z   <- mat$z[mat$sample==t][s]
      v0  <- mat$v0[mat$sample==t][s]
      b1v <- mat$b1v[mat$sample==t][s]
      b2v <- mat$b2v[mat$sample==t][s]
      ndt <- mat$ndt[mat$sample==t][s]
      
      tmp_df <- df %>% 
        filter(sub==s)
      
      nTrials <- nrow(tmp_df)
      d1 = tmp_df$d1-500
      d2 = tmp_df$d2-500
      cdur <- tmp_df$cdur
      cpos <- as.numeric(tmp_df$cpos)

      delta <-  v0 + b1v * d1 + b2v * d2
      
      for (i in 1:nTrials) {
        
        data <- data %>%
          add_row(dataset=t, sub=s,
                  d1=d1[i],d2=d2[i],cdur=cdur[i],cpos=cpos[i],
                  wienerProcess(v=delta[i], a=a, z=z, ndt=ndt))
        }
    }
  }
  return(data)
}
  
pred_m6 <- discrimination_ddm_sim(mat = mat)
```

###### Plotting
```{r}
summary <- df %>% 
  group_by(sub,
           cpos,
           cdur) %>% 
  summarise(prob_c=mean(resp)) %>% 
  mutate(cpos=as.factor(cpos),
         prob_c=prob_c-1)

summary$prob_c[summary$cpos==1] <- 1 - summary$prob_c[summary$cpos==1]

# summarize within dataset
summary_pred_m6 <- pred_m6 %>% 
  group_by(dataset,
           sub,
           cpos,
           cdur) %>% 
    summarise(prob_c=mean(resp))

# switcheroo
summary_pred_m6$prob_c[summary_pred_m6$cpos==2] <- 1 - summary_pred_m6$prob_c[summary_pred_m6$cpos==2]

# summarize over datasets
summary_pred_m6 <- summary_pred_m6 %>% 
  group_by(sub,
           cpos,
           cdur) %>%
  summarise(prob_c_quantile_low=quantile(prob_c,probs=0.025),
            prob_c_quantile_high=quantile(prob_c,probs=0.975),
            prob_c=mean(prob_c)) %>% 
  mutate(cpos=as.factor(cpos))

summary_pred_m6 %>% 
  ggplot(aes(x=cdur,
             y=prob_c,
             color=cpos,
             fill=cpos)) +
  # geom_point(shape=4)+
  # geom_line()+
  geom_ribbon(aes(ymin = prob_c_quantile_low,
                  ymax = prob_c_quantile_high,
                  fill=cpos),
              alpha=0.2,
              color=NA)+
  geom_point(data=summary,
             mapping=aes(x=cdur,
                         y=prob_c,
                         color=cpos))+
  geom_line(data=summary,
             mapping=aes(x=cdur,
                         y=prob_c,
                         color=cpos),
            linetype="dotted",
            alpha=0.5)+
  facet_wrap(~sub,nrow=4)+
  ggthemes::theme_tufte()+
  scale_color_manual(values = color_palette)+
  scale_fill_manual(values = color_palette)

```
